// <auto-generated />
using System;
using EfCoreMistakes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfCoreMistakes.Migrations
{
    [DbContext(typeof(EfCoreMistakesContext))]
    [Migration("20240602182524_postgresql.container_migration_226")]
    partial class postgresqlcontainer_migration_226
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EfCoreMistakes.Models.SomeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SomeModel");
                });

            modelBuilder.Entity("EfCoreMistakes.Models.SubModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SomeModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SomeModelId");

                    b.ToTable("SubModel");
                });

            modelBuilder.Entity("EfCoreMistakes.Models.SubModel", b =>
                {
                    b.HasOne("EfCoreMistakes.Models.SomeModel", null)
                        .WithMany("SubModels")
                        .HasForeignKey("SomeModelId");
                });

            modelBuilder.Entity("EfCoreMistakes.Models.SomeModel", b =>
                {
                    b.Navigation("SubModels");
                });
#pragma warning restore 612, 618
        }
    }
}
